from flask import Flask, request, jsonify
from crawl import crawl_and_extract_text
from summarize import summarize_with_openai

"""
A simple Flask application to handle web crawling and summarization requests.

Steps:
1. Main page should just show content/whatever
2. Url should be passed to the /summarize endpoint with POST requests
3. Then should return the summarized content

Main page is done, now we need to implement the /summarize in the file crawl.py
"""

app = Flask(__name__)

# / here, main page:
@app.get("/")
def showMainPage():
    # Just return the index.html page here also with css
    # Also lets center the text and make it look nice
    return """
    <html>
    <head>
        <title>Web Crawler and Summarizer</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                text-align: center;
                margin-top: 50px;
            }
            h1 {
                color: #333;
            }
            p {
                font-size: 18px;
            }
            a {
                color: #007BFF;
                text-decoration: none;
            }
            a:hover {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <h1>Welcome to the Web Crawler and Summarizer</h1>
        <p>This application allows you to crawl web pages and summarize their content.</p>
        <p>Use the <a href="/docs">API documentation</a> to interact with the crawler and summarizer.</p>
        <p>Usage:</p>
        <ul>
            <li>POST to <strong>/summarize</strong> with a URL to summarize its content.</li>
        </ul>
        <p>Check the <a href="/docs">API documentation</a> for more details.</p>
        <p>Developed with Flask.</p>
    </body>
    </html>
    """

@app.get("/docs")
def showDocs():
    # This should show the API documentation, which is automatically generated by Flask
    return """
    <html>
    <head>
        <title>API Documentation</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
            }
            h1 {
                color: #333;
            }
            ul {
                list-style-type: none;
            }
            li {
                margin: 10px 0;
            }
            strong {
                color: #007BFF;
            }
        </style>
    </head>
    <body>
        <h1>API Documentation</h1>
        <p>Use the following endpoints:</p>
        <ul>
            <li><strong>/</strong>: Main page</li>
            <li><strong>/summarize</strong>: POST request to summarize a URL</li>
        </ul>
    </body>
    </html>
    """

# /Summarize here:
@app.post("/summarize")
def summarize_url():
    data = request.get_json()
    if not data or 'url' not in data:
        return jsonify({"error": "No URL provided"}), 400

    url = data['url']
    if not url.startswith("https://"):
        return jsonify({"error": "URL must start with https://"}), 400

    content = crawl_and_extract_text(url)
    summary = summarize_with_openai(content)
    return jsonify({"summary": summary})

if __name__ == "__main__":
    app.run(debug=True, host='127.0.0.1', port=8000)